language: node_js
node_js:
  - "stable"
cache:
  directories:
  - node_modules
before_install:
  - cd play-our-song
script:
  - npm test
  - npm run build
after_success:
  - npm install -g firebase-tools
  - firebase use default
  - firebase deploy --token $FIREBASE_TOKEN --non-interactive